### ISSUE TITLE
config.server not configured on integration test

### ISSUE THREAD

**Issue by kayetter** [scottdurow/dataverse-ify#19]
I can't seem to get my config.server configured. When I run "jest integration" in terminal I get the following error:

> config.server not configured

      at Function.<anonymous> (node_modules/dataverse-ify/src/webapi/XrmStatic.ts:26:15)
      at node_modules/dataverse-ify/lib/webapi/XrmStatic.js:8:71
      at Object.<anonymous>.__awaiter (node_modules/dataverse-ify/lib/webapi/XrmStatic.js:4:12)
      at Function.createInstance (node_modules/dataverse-ify/lib/webapi/XrmStatic.js:17:16)
      at node_modules/dataverse-ify/src/webapi/SetupGlobalContext.ts:36:39
      at node_modules/dataverse-ify/lib/webapi/SetupGlobalContext.js:8:71

My configuration is as follows:
1. test.yaml file is present in a config folder directly under the root directory. Am I missing a step to configure credentials?
2. test.yaml contains the following configuration:
`nodewebapi:
logging: verbose
server:
host: https://[my environment].dynamics.com
version: 9.1`
however in the dataverse-ify integration instructions it says to use this:
`nodecds:
 server:
  host: https://someorg.crm11.dynamics.com
  version: 9.1`

3. `import { SetupGlobalContext } from "dataverse-ify/lib/webapi";` present in integration.AccountRibbon.test.ts
4. serviceClient set to `const serviceClient = new XrmContextCdsServiceClient(Xrm.WebApi);`
5. Ran npx node-cds-auth to get refreshToken

I tried updating the version in the test.yaml to 9.2. I also tried using a host = "https://[my environment].api.crm.dynamics.com"

Can you help me troubleshoot what I might be missing in my configuration?

**Comment by scottdurow** [comment]
Hi @kayetter - I think the issue here is that you are using node-cds-auth and the test.yaml for cdsify - but the integration test code for dataverse-ify.

I'd recommend using dataverse-ify rather that cdsify.

So you would ened to use the nodewebapi in your test.yaml, and use dataverse-auth

I've updated the docs which still had the old cdsify info which I suspect was the cause of confusion! 
- [Old integration testing with cdsify](https://github.com/scottdurow/dataverse-ify/wiki/Integration-testing-the-Xrm.WebApi-implementation/3a35bc217a0ce4d199f2e8e83363dde344e0608e)
- [Integration testing with dataverse-ify](https://github.com/scottdurow/dataverse-ify/wiki/Integration-testing-the-Xrm.WebApi-implementation)

**Comment by scottdurow** [comment]
Hi @kayetter you might have got round this by now - but it seems the issue could just be as simple as there being a trailing / in your test.yaml file.

Instead of:
```
nodewebapi:
 server:
  host: https://org.api.crm3.dynamics.com
  version: 9.1
```
Use:
```
nodewebapi:
 server:
  host: https://org.api.crm3.dynamics.com/
  version: 9.1
```

I'll add an issue to make dataverse-ify more forgiving of this!

**Comment by scottdurow** [comment]
Tracked in #21
